/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

CREATE TABLE `keyresults` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `objective_id` varchar(255) DEFAULT NULL,
  `KRcontent` varchar(255) DEFAULT NULL,
  `KRcompleted` tinyint(1) DEFAULT NULL,
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=57 DEFAULT CHARSET=utf8;

INSERT INTO `keyresults` (`id`, `objective_id`, `KRcontent`, `KRcompleted`) VALUES
(11, '13', '成果1.1', 0);
INSERT INTO `keyresults` (`id`, `objective_id`, `KRcontent`, `KRcompleted`) VALUES
(12, '13', '修改成果1.2', 1);
INSERT INTO `keyresults` (`id`, `objective_id`, `KRcontent`, `KRcompleted`) VALUES
(13, '13', '成果1.3', 1);
INSERT INTO `keyresults` (`id`, `objective_id`, `KRcontent`, `KRcompleted`) VALUES
(14, '14', '成果2.1', 0),
(15, '14', '成果2.2', 1),
(16, '15', '成果3.1', 0),
(40, '33', '成果4.1', 0),
(41, '33', '成果4.2', 0);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;